### ISSUE TITLE
Babel extractor doesn't work

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/asknot-ng#146]
I tried to extract new pot with updated strings using the [guide](https://github.com/fedora-infra/asknot-ng#preparing-translations) in README.md.

The extractor fails with following:
```
running extract_messages
extracting messages from questions/coala.yml
Traceback (most recent call last):
  File "/var/home/zlopez/git/asknot-ng/setup.py", line 5, in <module>
    setup(
  File "/var/home/zlopez/git/asknot-ng/.venv/lib64/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/var/home/zlopez/git/asknot-ng/.venv/lib64/python3.10/site-packages/babel/messages/frontend.py", line 481, in run
    for filename, lineno, message, comments, context in extracted:
  File "/var/home/zlopez/git/asknot-ng/.venv/lib64/python3.10/site-packages/babel/messages/extract.py", line 149, in extract_from_dir
    for message_tuple in check_and_call_extract_file(
  File "/var/home/zlopez/git/asknot-ng/.venv/lib64/python3.10/site-packages/babel/messages/extract.py", line 207, in check_and_call_extract_file
    for message_tuple in extract_from_file(
  File "/var/home/zlopez/git/asknot-ng/.venv/lib64/python3.10/site-packages/babel/messages/extract.py", line 243, in extract_from_file
    return list(extract(method, fileobj, keywords, comment_tags,
  File "/var/home/zlopez/git/asknot-ng/.venv/lib64/python3.10/site-packages/babel/messages/extract.py", line 320, in extract
    raise ValueError('Unknown extraction method %r' % method)
ValueError: Unknown extraction method 'asknot'
```

I tried to look at the issue, but I wasn't able to understand how the `entry_points` for `babel` actually works.

**Comment by hhlp** [comment]
@zlopez I don't get any message normal Workstation here, with the procedure explained below works well here:

python setup.py extract_messages --output-file l10n/fedora/locale/asknot-ng.pot --input-dir=.        

```                                                                                                            
running extract_messages                                                                                   
extracting messages from questions/coala.yml                                                               
extracting messages from questions/fedora.yml                                                              
extracting messages from questions/gnome.yml                                                               
extracting messages from questions/includes/fedora/advocacy.yml                                            
extracting messages from questions/includes/fedora/cloud.yml                                               
extracting messages from questions/includes/fedora/coding.yml
extracting messages from questions/includes/fedora/community.yml
extracting messages from questions/includes/fedora/design.yml                                              
extracting messages from questions/includes/fedora/desktop.yml                                             
extracting messages from questions/includes/fedora/i18n.yml                                                
extracting messages from questions/includes/fedora/packaging.yml                                           
extracting messages from questions/includes/fedora/qa.yml                                                  
extracting messages from questions/includes/fedora/server.yml                                              
extracting messages from questions/includes/fedora/translation.yml                                         
extracting messages from questions/includes/fedora/writing.yml                                             
extracting messages from questions/includes/fedora/coding/c++.yml
extracting messages from questions/includes/fedora/coding/c.yml
extracting messages from questions/includes/fedora/coding/haskell.yml
extracting messages from questions/includes/fedora/coding/java.yml
extracting messages from questions/includes/fedora/coding/python.yml
extracting messages from questions/includes/fedora/coding/scala.yml
extracting messages from questions/includes/fedora/coding/web.yml
writing PO template file to l10n/fedora/locale/asknot-ng.pot
```

python code

```
from setuptools import setup

line 5 -> setup(
```

see:

https://stackoverflow.com/questions/57826842/how-to-fix-valueerror-unknown-extraction-method-jinja2-error-in-python-j

-> reinstall babel library manually using pip package manager.

https://stackoverflow.com/questions/12046998/babel-doesnt-recognize-jinja2-extraction-method-for-language-support

-> upgrade setuptools -> sudo pip install --upgrade setuptools

pip list

Babel                         2.9.1
setuptools                    57.4.0

Regards.,

**Comment by Zlopez** [comment]
Are you running python 3.10?

I tried to update the setuptools, but I still have the same issue. Following is the list of packages in virtual environment.
```
$ pip list
Package    Version
---------- -------
Babel      2.9.1
coverage   6.1.1
Jinja2     3.0.2
Mako       1.1.5
MarkupSafe 2.0.1
nose       1.3.7
nose2      0.10.0
pip        21.2.3
pytz       2021.3
PyYAML     6.0
setuptools 58.5.2
six        1.16.0
```

**Comment by hhlp** [comment]
Yes ., Fedora 35

```
pip show setuptools
Name: setuptools
Version: 57.4.0
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: UNKNOWN
Location: /usr/lib/python3.10/site-packages
Requires: 
Required-by: zope.interface, setools, python-Levenshtein, zope.event, wadllib, spyder, Sphinx, Rtree, python-lsp-server, Paste, nmstate, lazr.uri, lazr.restfulclient, launchpadlib, jsonschema, ipython, google-auth, google-api-core, fs, copr-cli, bodhi, astroid
```

This is my list in venv, this is all you need to work:

```
asknot-ng  1.0     /home/hhlp/asknot-ng                                         
Babel      2.9.1                                                                
Mako       1.1.5                                                                
MarkupSafe 2.0.1                                                                
pip        21.2.3                                                               
pytz       2021.3
PyYAML     6.0
setuptools 57.4.0
wheel      0.36.2
```

setupptools diferent to yours in my case took from system environment.

```
rpm -qa python3-setuptools  

python3-setuptools-57.4.0-1.fc35.noarch
```

Regards.,

**Comment by Zlopez** [comment]
I found out, I was missing the `asknot-ng` itself. Thanks for helping me
